apiVersion: v1
kind: Service
metadata:
  name: ecoloop-backend
  namespace: ecoloop
spec:
  selector:
    app: ecoloop-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
