apiVersion: v1
kind: Service
metadata:
  name: ecoloop-frontend
  namespace: ecoloop
spec:
  selector:
    app: ecoloop-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
