apiVersion: v1
kind: Service
metadata:
  name: ecoloop-db
  namespace: ecoloop
spec:
  selector:
    app: ecoloop-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
