apiVersion: v1
kind: Secret
metadata:
  name: ecoloop-secrets
  namespace: ecoloop
type: Opaque
stringData:
  POSTGRES_USER: ecoloop
  POSTGRES_PASSWORD: ecoloop_secret
  DATABASE_URL: postgresql://ecoloop:ecoloop_secret@ecoloop-db:5432/ecoloop
  JWT_SECRET: cambia_esto_por_algo_seguro
